# Generated by Powerlevel10k configuration wizard on 2024-03-10.
# Based on romkatv/powerlevel10k/config/p10k-rainbow.zsh, checksum 47892.
#
# When you're done editing this file, run "p10k reload"
#
# Tip: Looking for a nice color? Search for "p10k color" in Zsh:
#   for i in {0..255}; do print -P "%F{$i}This is color $i%f"; done

# Temporarily change options.
'builtin' 'local' '-a' 'p10k_config_opts'
[[ ! -o 'aliases'         ]] || p10k_config_opts+=('aliases')
[[ ! -o 'sh_word_split'   ]] || p10k_config_opts+=('sh_word_split')
[[ ! -o 'pushd_silent'    ]] || p10k_config_opts+=('pushd_silent')
[[ ! -o 'prompt_subst'    ]] || p10k_config_opts+=('prompt_subst')
'builtin' 'setopt' 'no_aliases' 'no_sh_word_split' 'pushd_silent' 'prompt_subst'

# General settings
typeset -g POWERLEVEL9K_MODE='nerdfont-complete'
typeset -g POWERLEVEL9K_PROMPT_ON_NEWLINE=true
typeset -g POWERLEVEL9K_DIR_ANCHOR_FOREGROUND=255
typeset -g POWERLEVEL9K_DIR_ANCHOR_BACKGROUND=4
typeset -g POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX='%238F─╮'
typeset -g POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX='%238F╰─ %238F%B%F{238}❯%b%f '
typeset -g POWERLEVEL9K_PROMPT_ADD_NEWLINE=true
typeset -g POWERLEVEL9K_TRANSIENT_PROMPT=always

# Left prompt segments
typeset -g POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(
  os_icon                 # os identifier
  dir                     # current directory
  vcs                     # git status
  # virtualenv              # python virtual environment
)

# Right prompt segments
typeset -g POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(
  status                  # exit code of the last command
  command_execution_time  # duration of the last command
  background_jobs         # presence of background jobs
  time                    # current time
  # ip                      # ip address
  # public_ip
  # load
  # ram
)

# `os_icon` segment
typeset -g POWERLEVEL9K_OS_ICON_BACKGROUND=238

# `dir` segment
typeset -g POWERLEVEL9K_DIR_FOREGROUND=31
typeset -g POWERLEVEL9K_SHORTEN_DIR_LENGTH=1
typeset -g POWERLEVEL9K_SHORTEN_STRATEGY="truncate_to_unique"

# `vcs` (git) segment
typeset -g POWERLEVEL9K_VCS_FOREGROUND=229
typeset -g POWERLEVEL9K_VCS_MODIFIED_BACKGROUND=3
typeset -g POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND=229

# `status` segment
typeset -g POWERLEVEL9K_STATUS_OK_FOREGROUND=46
typeset -g POWERLEVEL9K_STATUS_OK_BACKGROUND=238
typeset -g POWERLEVEL9K_STATUS_ERROR_FOREGROUND=196
typeset -g POWERLEVEL9K_STATUS_ERROR_BACKGROUND=238

# `command_execution_time` segment
typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_FOREGROUND=108
typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_BACKGROUND=238

# `background_jobs` segment
typeset -g POWERLEVEL9K_BACKGROUND_JOBS_FOREGROUND=48
typeset -g POWERLEVEL9K_BACKGROUND_JOBS_BACKGROUND=238

# `time` segment
typeset -g POWERLEVEL9K_TIME_FOREGROUND=66
typeset -g POWERLEVEL9K_TIME_BACKGROUND=238

# `virtualenv` segment
typeset -g POWERLEVEL9K_VIRTUALENV_FOREGROUND=37
typeset -g POWERLEVEL9K_VIRTUALENV_BACKGROUND=238


# Unset all configuration options.
'builtin' 'unset' 'p10k_config_opts'